// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHZBRaerI6QgWgTpaLD2EHPGZJXUYeBew',
    appId: '1:459962607492:web:8ebd76dbeba4286e9d5fd1',
    messagingSenderId: '459962607492',
    projectId: 'food-share-fce9b',
    authDomain: 'food-share-fce9b.firebaseapp.com',
    databaseURL: 'https://food-share-fce9b-default-rtdb.firebaseio.com',
    storageBucket: 'food-share-fce9b.firebasestorage.app',
    measurementId: 'G-VTFYZFNRFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKZW-qmXBVIDMPMmVyFG-AWr9JI_fO03g',
    appId: '1:459962607492:android:8a6806fa57470e5b9d5fd1',
    messagingSenderId: '459962607492',
    projectId: 'food-share-fce9b',
    databaseURL: 'https://food-share-fce9b-default-rtdb.firebaseio.com',
    storageBucket: 'food-share-fce9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn2jP6LNWuHkeoVJwQ_llyRzl0K_yNXEM',
    appId: '1:459962607492:ios:0cd668f34487cb769d5fd1',
    messagingSenderId: '459962607492',
    projectId: 'food-share-fce9b',
    databaseURL: 'https://food-share-fce9b-default-rtdb.firebaseio.com',
    storageBucket: 'food-share-fce9b.firebasestorage.app',
    iosBundleId: 'com.example.foodShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn2jP6LNWuHkeoVJwQ_llyRzl0K_yNXEM',
    appId: '1:459962607492:ios:0cd668f34487cb769d5fd1',
    messagingSenderId: '459962607492',
    projectId: 'food-share-fce9b',
    databaseURL: 'https://food-share-fce9b-default-rtdb.firebaseio.com',
    storageBucket: 'food-share-fce9b.firebasestorage.app',
    iosBundleId: 'com.example.foodShare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHZBRaerI6QgWgTpaLD2EHPGZJXUYeBew',
    appId: '1:459962607492:web:f5cfd5e568c8bc339d5fd1',
    messagingSenderId: '459962607492',
    projectId: 'food-share-fce9b',
    authDomain: 'food-share-fce9b.firebaseapp.com',
    databaseURL: 'https://food-share-fce9b-default-rtdb.firebaseio.com',
    storageBucket: 'food-share-fce9b.firebasestorage.app',
    measurementId: 'G-5KQPY34JXE',
  );

}